# Common
random_seed: 42

learning_rate: 0.001 # Input model's learning rate

model_type: 'Pytorch' # This value should be maintained
model:
  _target_: models.MNISTClassifier # Input your custom model
  output_size: 10 # Input your model's output size (only classification)

xai_enabled: disabled
dataset:
    name: 'MNIST' # Input your data name
    validation_split: 0.2 # Ratio of dividing train data by validation


# client
task_id: 'samd' # Input your Task Name that you register in FedOps Website

wandb: 
  use: false # Whether to use wandb
  key: 'your wandb api key' # Input your wandb api key
  account: 'your wandb account' # Input your wandb account
  project: '${dataset.name}_${task_id}'

# server
num_epochs: 1 # number of local epochs
batch_size: 128
num_rounds: 2 # Number of rounds to perform
clients_per_round: 1 # Number of clients participating in the round

server:
  strategy:
    _target_: flwr.server.strategy.FedProx # aggregation algorithm
    proximal_mu: 0.01
    min_fit_clients: ${clients_per_round} # Minimum number of clients to participate in training
    min_available_clients: ${clients_per_round} # Minimum number of clients to participate in a round
    min_evaluate_clients: ${clients_per_round} # Minimum number of clients to participate in evaluation

# Additional configurations
data_type: 'Image'
client_type: 'Silo(PC)'
server_repo_addr: ''
